# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AvNightly < Formula
  desc ""
  homepage "https://aviator.co"
  version "0.1.44-rc1-nightly"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/av/releases/download/v0.1.44-rc1-nightly/av_0.1.44-rc1-nightly_darwin_x86_64.tar.gz"
      sha256 "aec5291959fac2e94e7cfc28744bc45d7c4a7ef47413334ac642b520575bf19f"

      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviator-co/av/releases/download/v0.1.44-rc1-nightly/av_0.1.44-rc1-nightly_darwin_arm64.tar.gz"
      sha256 "73f52c8403c4b09692084bd75e4a1ac0280bc07711a38d5e286579ebf8bd092f"

      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/av/releases/download/v0.1.44-rc1-nightly/av_0.1.44-rc1-nightly_linux_x86_64.tar.gz"
      sha256 "ab61b44cab7a3c647b607714186607b8c28cae86e5f7c7551470d13c39867598"
      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/av/releases/download/v0.1.44-rc1-nightly/av_0.1.44-rc1-nightly_linux_arm64.tar.gz"
      sha256 "8ad5edfabc5f551c18ba952154d76fd81aebf081bac420cb1787b93e36828022"
      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end
end
