# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AvNightly < Formula
  desc ""
  homepage "https://aviator.co"
  version "0.1.38-rc1-nightly"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/av/releases/download/v0.1.38-rc1-nightly/av_0.1.38-rc1-nightly_darwin_x86_64.tar.gz"
      sha256 "537f4e2a898bbcc101885fdaad3cc87e646c3bb1430165f0b5f3733915c8f2cc"

      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviator-co/av/releases/download/v0.1.38-rc1-nightly/av_0.1.38-rc1-nightly_darwin_arm64.tar.gz"
      sha256 "935b7c1d85d3f7b94b728c0beda8329dc0fa76275837a5c1973c34316b2e783b"

      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/av/releases/download/v0.1.38-rc1-nightly/av_0.1.38-rc1-nightly_linux_x86_64.tar.gz"
      sha256 "e28199d8a31ea5078d4180f4730fc01c0843900adc045087e58269a0e7d82590"
      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/av/releases/download/v0.1.38-rc1-nightly/av_0.1.38-rc1-nightly_linux_arm64.tar.gz"
      sha256 "17655996598f0af6205edd7c49dd8debd70b9a87b9b34d62638eaadd44c9c165"
      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end
end
