# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AvNightly < Formula
  desc ""
  homepage "https://aviator.co"
  version "0.1.28-rc1-nightly"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/av/releases/download/v0.1.28-rc1-nightly/av_0.1.28-rc1-nightly_darwin_x86_64.tar.gz"
      sha256 "e99ada69689351dc43fd39bdf912aa7402add81f115f3729310c25a49e9587c2"

      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviator-co/av/releases/download/v0.1.28-rc1-nightly/av_0.1.28-rc1-nightly_darwin_arm64.tar.gz"
      sha256 "c974d56b975c12c3f30039a2221a31beedac9686ce751c1ea34252e56eac472c"

      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/av/releases/download/v0.1.28-rc1-nightly/av_0.1.28-rc1-nightly_linux_x86_64.tar.gz"
      sha256 "7d7988ba26a1bfc29396007567660da7aa17609c0137be12fa82c1737b8dc7df"
      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/av/releases/download/v0.1.28-rc1-nightly/av_0.1.28-rc1-nightly_linux_arm64.tar.gz"
      sha256 "201f52621334cdae2ee5d30e97a2fa4f593ed17978440a871619c1c40f977a09"
      define_method(:install) do
        bin.install "av"
        man.install Dir["man/*"]
        generate_completions_from_executable(bin/"av", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end
end
