# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Av < Formula
  desc ""
  homepage "https://aviator.co"
  version "0.0.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/av/releases/download/v0.0.17/av_0.0.17_darwin_x86_64.tar.gz"
      sha256 "f5ff317845cc0b958fc1a0ea5ff0ecd4eae80dfbafc75edf90f64b28403b7627"

      def install
        bin.install "av"
        man.install Dir["man/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviator-co/av/releases/download/v0.0.17/av_0.0.17_darwin_arm64.tar.gz"
      sha256 "065faa13dd4bbcb6834be429bf830f83ff3fc6c82371d1492ffa9c6cb95774cc"

      def install
        bin.install "av"
        man.install Dir["man/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/av/releases/download/v0.0.17/av_0.0.17_linux_arm64.tar.gz"
      sha256 "d4827e7dc582198fecb9921fcfcf404b9e6730b676a0c66516a554ecf868a247"

      def install
        bin.install "av"
        man.install Dir["man/*"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/av/releases/download/v0.0.17/av_0.0.17_linux_x86_64.tar.gz"
      sha256 "29603ec085493f3f7c0cfcfc051d5ff741c51e8fa3345b22c99197d11d512023"

      def install
        bin.install "av"
        man.install Dir["man/*"]
      end
    end
  end
end
