# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Av < Formula
  desc ""
  homepage "https://aviator.co"
  version "0.0.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aviator-co/av/releases/download/v0.0.14/av_0.0.14_macos_arm64.tar.gz"
      sha256 "b14e35646ff05f9511e5167cf22372428626e0efc3084800caa046f6a1ca8552"

      def install
        bin.install "av"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/av/releases/download/v0.0.14/av_0.0.14_macos_x86_64.tar.gz"
      sha256 "17bbe9b7f0d374eb846c639110a5a6c4b9bc8dd326224b909f361c45a006644f"

      def install
        bin.install "av"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/av/releases/download/v0.0.14/av_0.0.14_linux_x86_64.tar.gz"
      sha256 "36aa841490095d9b3087a18dbb655b1f7c6901cd847d3a4075d6ff2eb783bec1"

      def install
        bin.install "av"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/av/releases/download/v0.0.14/av_0.0.14_linux_arm64.tar.gz"
      sha256 "c4e160b1047f168c64a842c62dff67d30111ebda92a5dd932cbf4ff48320bc48"

      def install
        bin.install "av"
      end
    end
  end
end
