# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Av < Formula
  desc ""
  homepage "https://aviator.co"
  version "0.0.1-beta4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/av/releases/download/v0.0.1-beta4/av_0.0.1-beta4_darwin_amd64.tar.gz"
      sha256 "3519b30b9a3a4b125ac5f14e9374c66ed8d6a2007dbf524413a0f6a8d67a9ccd"

      def install
        bin.install "av"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviator-co/av/releases/download/v0.0.1-beta4/av_0.0.1-beta4_darwin_arm64.tar.gz"
      sha256 "22a27010a6ad6e68ec40704877c76089a507c14fe84474a5456388a2424dfc20"

      def install
        bin.install "av"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/av/releases/download/v0.0.1-beta4/av_0.0.1-beta4_linux_arm64.tar.gz"
      sha256 "391b6856964f588ecda1ab4a057212a7d1f7bcb085fb1564b0f3d94e7806b4f1"

      def install
        bin.install "av"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/av/releases/download/v0.0.1-beta4/av_0.0.1-beta4_linux_amd64.tar.gz"
      sha256 "caf32cece703e8decbaa067675d574f5189e5e4a534bbbffb9cef6a880eb2cc4"

      def install
        bin.install "av"
      end
    end
  end
end
