# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aviator < Formula
  desc "CLI tool to submit verifications and create runbooks on Aviator."
  homepage "https://aviator.co"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.3/aviator-cli_0.0.3_darwin_x86_64.tar.gz"
      sha256 "6a1d4ff976bb4e91f8e3e5341e4c12b79e1cd905878bf590d129ee8bd21a2ae0"

      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.3/aviator-cli_0.0.3_darwin_arm64.tar.gz"
      sha256 "8fb99b796f354c96dc1be032b5e78247349285ae2e206fe38e03e10b0cdf458d"

      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.3/aviator-cli_0.0.3_linux_x86_64.tar.gz"
      sha256 "089b086e0b34d02e0f7ed6d330c3a7eea1ed1b352775b198433a07ed67d63bff"
      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.3/aviator-cli_0.0.3_linux_arm64.tar.gz"
      sha256 "e1b76bb0c7cfd4506b3fe455419f0ec62d79c1b330034891a95877432de094f1"
      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end
end
