# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aviator < Formula
  desc "CLI tool to submit verifications and create runbooks on Aviator."
  homepage "https://aviator.co"
  version "0.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.18/aviator-cli_0.0.18_darwin_x86_64.tar.gz"
      sha256 "c265efe86a9ad092aaf1b97803792b9659247210d35457871b9d7515a4c7ba29"

      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.18/aviator-cli_0.0.18_darwin_arm64.tar.gz"
      sha256 "1f16e2420ff80b84b939a1f04543b29738a73e9532640134c070c754341ba564"

      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.18/aviator-cli_0.0.18_linux_x86_64.tar.gz"
      sha256 "53ca8c95f91fbb03a1218eaf3b5e3d8ae9c0447bd23eb0c1e6f7b5971fdf53d2"
      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.18/aviator-cli_0.0.18_linux_arm64.tar.gz"
      sha256 "64686341aaf49ce1a4a5ff66f760569dbb2dd0c1d941e42db8b198340083cd35"
      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end
end
