# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AviatorNightly < Formula
  desc "CLI tool to submit verifications and create runbooks on Aviator (nightly build)."
  homepage "https://aviator.co"
  version "0.0.3-rc1-nightly"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.3-rc1-nightly/aviator-cli_0.0.3-rc1-nightly_darwin_x86_64.tar.gz"
      sha256 "4bbc78a7335a612bda3e4af289e2500f1084cf02c6517984c2fc74ae1c54586c"

      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.3-rc1-nightly/aviator-cli_0.0.3-rc1-nightly_darwin_arm64.tar.gz"
      sha256 "a2bfb1a2efa979cf92bf09f2fdf3d73aa93939359e111f0139a2397e8a01efc1"

      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.3-rc1-nightly/aviator-cli_0.0.3-rc1-nightly_linux_x86_64.tar.gz"
      sha256 "ee071c5d5a91d4157e93e715befbf6cae66c0a631ec1ed098d2afe9f5c7823ac"
      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.3-rc1-nightly/aviator-cli_0.0.3-rc1-nightly_linux_arm64.tar.gz"
      sha256 "b0decae92e3eeb8f4948e17f0bb34439169c33b858d2779467450e8415ec8d35"
      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end
end
