# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AviatorNightly < Formula
  desc "CLI tool to submit verifications and create runbooks on Aviator (nightly build)."
  homepage "https://aviator.co"
  version "0.0.15-rc1-nightly"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.15-rc1-nightly/aviator-cli_0.0.15-rc1-nightly_darwin_x86_64.tar.gz"
      sha256 "32d545ac9990e15e3400fb0c324b6782a2cb1e1288a922d5974ba273eb4856c3"

      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.15-rc1-nightly/aviator-cli_0.0.15-rc1-nightly_darwin_arm64.tar.gz"
      sha256 "02d0d9656461a176d28f89cfa9089a3452757c4a5c03b7024f085bfef2465cf1"

      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.15-rc1-nightly/aviator-cli_0.0.15-rc1-nightly_linux_x86_64.tar.gz"
      sha256 "c789af898efc35c0969163791683415a22e332785e241c63e110ec71ba779f70"
      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.15-rc1-nightly/aviator-cli_0.0.15-rc1-nightly_linux_arm64.tar.gz"
      sha256 "0006191fb391b55a4d186855e38d2526d684f86e14b23687b225980905be75ca"
      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end
end
