# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aviator < Formula
  desc "CLI tool to submit verifications and create runbooks on Aviator."
  homepage "https://aviator.co"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.1/aviator-cli_0.0.1_darwin_x86_64.tar.gz"
      sha256 "ec330f5b53e6b72e3866dd1d5003c81b857381aac008283b455dc6b144f45610"

      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.1/aviator-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "5575d58e1cfdfb8c93508bb463d6f55e8185f547b75cd4d17d5f4eea79b3e26d"

      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.1/aviator-cli_0.0.1_linux_x86_64.tar.gz"
      sha256 "7dae85fd077f18abf2b14f5e69244864a702f70ccbe041e132df4f86608e37d9"
      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviator-co/aviator-cli/releases/download/v0.0.1/aviator-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "79eeb3a7408a82831938fcf9f5bf50035cccd9ace62b540a965440285a766243"
      define_method(:install) do
        bin.install "aviator"
        generate_completions_from_executable(bin/"aviator", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end
end
